### PR TITLE
Compatibility with MoPub > 5.13

### PR DESCRIPTION
**Pull request by fdobjenschi**
----

### CODE REVIEW

**Comment by DamienRivetOgury** [comment]
Hi @FlorinDob,

Could you explain what you did here and why you did it?

Screenshot 2021-05-14 at 10 56 52

**Review by ghost — CHANGES_REQUESTED** [review]
-----

**Comment by fdobjenschi** [comment]
> Hi @FlorinDob,
> 
> Could you explain what you did here and why you did it?
> 
> Screenshot 2021-05-14 at 10 56 52

The repo has been recreated at 'Merge commit'  that's why appears like that on your side .

**Comment by DamienRivetOgury** [comment]
> > Hi @FlorinDob,
> > Could you explain what you did here and why you did it?
> > Screenshot 2021-05-14 at 10 56 52
> 
> The repo has been recreated at 'Merge commit' that's why appears like that on your side .

Yup, I deduced this but what's the point of using Git if you rewrite the history completely? Let's just supply the sample code through an archive on S3, less hassle for you.

Will you rewrite the whole history each time something is merged on `master`?

**Comment by fdobjenschi** [comment]
No , from now we will just merge .
At the beginning did not liked how the history looked and i asked devops to recreate the repo.

**Comment by DamienRivetOgury** [comment]
> No , from now we will just merge .
> At the beginning did not liked how the history looked and i asked devops to recreate the repo.

What I don't understand is why do you need to repo then? Why not upload the end result directly on a S3 folder and update it only when needed.

Since you don't want the history to look messy, which will invariably happen, let's just skype this "extra" step no?

**Comment by fdobjenschi** [comment]
This way with GitHub is more dev friendly then an S3 folder and also it helps to keep versions of sample apps more easy .
Also helps a lot on the support side and we have to follow other bigger networks are doing with sample apps .

**Comment by DamienRivetOgury** [comment]
> This way with GitHub is more dev friendly than an S3 folder and also it helps to keep versions of sample apps more easy .
> Also helps a lot on the support side and we have to follow other bigger networks are doing with sample apps .

As you wish, but what's the point of reviewing PR for this repo if in the end, everything can be overwritten if it looks messy?

I do get the point, technically speaking, but it would be better to have one public repo with only commits on `master` and a private repo for actually working on the sample Apps together with PRs & meaningful validation.

What's I'm afraid of is loosing the point of using Git if anything can be simply discarded to restart anew. What's the point of performing PR reviews then?

**Pull request closed without merging**
